# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Call for papers"
  url = "call_papers/"
  weight = 30

[[main]]
  name = "Submission"
  url = "submission/"
  weight = 35

[[main]]
  name = "Program"
  url = "program/"
  weight = 40

[[main]]
  name = "Attend"
  url = "attend/"
  weight = 42

[[main]]
  name = "Graduate School"
  url = "school/"
  weight = 45

[[main]]
  name = "Awards"
  url = "awards/"
  weight = 70

[[main]]
  name = "Ph.D. Consortium"
  url = "consortium/"
  weight = 80

[[main]]
  name = "Organizers"
  url = "organizers/"
  weight = 100
